// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type Consent struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	OrgID        uuid.UUID `json:"org_id"`
	DocumentType string    `json:"document_type"`
	Version      string    `json:"version"`
	CreatedAt    time.Time `json:"created_at"`
}

type Department struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
	Name  string    `json:"name"`
}

type Document struct {
	ID        uuid.UUID `json:"id"`
	Type      string    `json:"type"`
	Version   string    `json:"version"`
	Url       string    `json:"url"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
}

type Employee struct {
	ID           uuid.UUID `json:"id"`
	OrgID        uuid.UUID `json:"org_id"`
	UserID       uuid.UUID `json:"user_id"`
	DepartmentID uuid.UUID `json:"department_id"`
	PositionID   uuid.UUID `json:"position_id"`
	Role         string    `json:"role"`
	SalaryRate   string    `json:"salary_rate"`
	Status       string    `json:"status"`
}

type Organization struct {
	ID          uuid.UUID `json:"id"`
	AdminID     uuid.UUID `json:"admin_id"`
	Name        string    `json:"name"`
	VatID       string    `json:"vat_id"`
	Description string    `json:"description"`
	Address     string    `json:"address"`
	CityID      int32     `json:"city_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type Position struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
	Name  string    `json:"name"`
}

type User struct {
	ID                 uuid.UUID `json:"id"`
	OrgID              uuid.UUID `json:"org_id"`
	Email              string    `json:"email"`
	Role               string    `json:"role"`
	FirstName          string    `json:"first_name"`
	LastName           string    `json:"last_name"`
	PhoneNumber        string    `json:"phone_number"`
	VerificationStatus string    `json:"verification_status"`
	CreatedAt          time.Time `json:"created_at"`
}
