// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const getActiveDocuments = `-- name: GetActiveDocuments :many
SELECT type, version, url
FROM documents
WHERE is_active = true
`

type GetActiveDocumentsRow struct {
	Type    string `json:"type"`
	Version string `json:"version"`
	Url     string `json:"url"`
}

func (q *Queries) GetActiveDocuments(ctx context.Context) ([]GetActiveDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveDocumentsRow{}
	for rows.Next() {
		var i GetActiveDocumentsRow
		if err := rows.Scan(&i.Type, &i.Version, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminIDByOrgID = `-- name: GetAdminIDByOrgID :one
SELECT admin_id FROM organizations WHERE id = $1
`

func (q *Queries) GetAdminIDByOrgID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getAdminIDByOrgID, id)
	var admin_id uuid.UUID
	err := row.Scan(&admin_id)
	return admin_id, err
}

const getConsentsByOrgID = `-- name: GetConsentsByOrgID :many
SELECT DISTINCT ON (document_type) document_type, version
FROM consents
WHERE org_id = $1
ORDER BY document_type, created_at DESC
`

type GetConsentsByOrgIDRow struct {
	DocumentType string `json:"document_type"`
	Version      string `json:"version"`
}

func (q *Queries) GetConsentsByOrgID(ctx context.Context, orgID uuid.UUID) ([]GetConsentsByOrgIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getConsentsByOrgID, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConsentsByOrgIDRow{}
	for rows.Next() {
		var i GetConsentsByOrgIDRow
		if err := rows.Scan(&i.DocumentType, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestDocumentVersions = `-- name: GetLatestDocumentVersions :many
SELECT type, version
FROM documents
WHERE is_active = true
`

type GetLatestDocumentVersionsRow struct {
	Type    string `json:"type"`
	Version string `json:"version"`
}

func (q *Queries) GetLatestDocumentVersions(ctx context.Context) ([]GetLatestDocumentVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatestDocumentVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLatestDocumentVersionsRow{}
	for rows.Next() {
		var i GetLatestDocumentVersionsRow
		if err := rows.Scan(&i.Type, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertConsentForOrg = `-- name: InsertConsentForOrg :exec
INSERT INTO consents (id, user_id, org_id, document_type, version, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
`

type InsertConsentForOrgParams struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	OrgID        uuid.UUID `json:"org_id"`
	DocumentType string    `json:"document_type"`
	Version      string    `json:"version"`
}

func (q *Queries) InsertConsentForOrg(ctx context.Context, arg InsertConsentForOrgParams) error {
	_, err := q.db.ExecContext(ctx, insertConsentForOrg,
		arg.ID,
		arg.UserID,
		arg.OrgID,
		arg.DocumentType,
		arg.Version,
	)
	return err
}
