// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetActiveDocuments(ctx context.Context) ([]GetActiveDocumentsRow, error)
	GetAdminIDByOrgID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetConsentsByOrgID(ctx context.Context, orgID uuid.UUID) ([]GetConsentsByOrgIDRow, error)
	GetLatestDocumentVersions(ctx context.Context) ([]GetLatestDocumentVersionsRow, error)
	InsertConsentForOrg(ctx context.Context, arg InsertConsentForOrgParams) error
}

var _ Querier = (*Queries)(nil)
