// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteSessionByRefreshToken(ctx context.Context, refreshToken string) error
	DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error
	GetSessionByRefreshToken(ctx context.Context, refreshToken string) (GetSessionByRefreshTokenRow, error)
	InsertUserSession(ctx context.Context, arg InsertUserSessionParams) error
}

var _ Querier = (*Queries)(nil)
