// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteSessionByRefreshToken = `-- name: DeleteSessionByRefreshToken :exec
DELETE FROM user_sessions
WHERE refresh_token = $1
`

func (q *Queries) DeleteSessionByRefreshToken(ctx context.Context, refreshToken string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByRefreshToken, refreshToken)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM user_sessions
WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUserID, userID)
	return err
}

const getSessionByRefreshToken = `-- name: GetSessionByRefreshToken :one
SELECT id, user_id, cognito_username, refresh_token, expires_at
FROM user_sessions
WHERE refresh_token = $1
  AND expires_at > NOW()
`

type GetSessionByRefreshTokenRow struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	CognitoUsername string    `json:"cognito_username"`
	RefreshToken    string    `json:"refresh_token"`
	ExpiresAt       time.Time `json:"expires_at"`
}

func (q *Queries) GetSessionByRefreshToken(ctx context.Context, refreshToken string) (GetSessionByRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByRefreshToken, refreshToken)
	var i GetSessionByRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CognitoUsername,
		&i.RefreshToken,
		&i.ExpiresAt,
	)
	return i, err
}

const insertUserSession = `-- name: InsertUserSession :exec
INSERT INTO user_sessions (id, user_id, cognito_username, refresh_token, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertUserSessionParams struct {
	ID              uuid.UUID `json:"id"`
	UserID          uuid.UUID `json:"user_id"`
	CognitoUsername string    `json:"cognito_username"`
	RefreshToken    string    `json:"refresh_token"`
	ExpiresAt       time.Time `json:"expires_at"`
}

func (q *Queries) InsertUserSession(ctx context.Context, arg InsertUserSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertUserSession,
		arg.ID,
		arg.UserID,
		arg.CognitoUsername,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	return err
}
