// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckEmployeeExists(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteEmployee(ctx context.Context, id uuid.UUID) error
	GetEmployeeByID(ctx context.Context, id uuid.UUID) (GetEmployeeByIDRow, error)
	GetEmployeesByOrgID(ctx context.Context, orgID uuid.UUID) ([]GetEmployeesByOrgIDRow, error)
	GetOrgIDByUserID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	InsertEmployee(ctx context.Context, arg InsertEmployeeParams) error
	UpdateEmployeeDepartment(ctx context.Context, arg UpdateEmployeeDepartmentParams) error
	UpdateEmployeePosition(ctx context.Context, arg UpdateEmployeePositionParams) error
	UpdateEmployeeRole(ctx context.Context, arg UpdateEmployeeRoleParams) error
	UpdateEmployeeSalary(ctx context.Context, arg UpdateEmployeeSalaryParams) error
	UpdateEmployeeStatus(ctx context.Context, arg UpdateEmployeeStatusParams) error
}

var _ Querier = (*Queries)(nil)
