// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const checkEmployeeExists = `-- name: CheckEmployeeExists :one
SELECT COUNT(*)
FROM employees
WHERE id = $1
`

func (q *Queries) CheckEmployeeExists(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkEmployeeExists, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEmployee = `-- name: DeleteEmployee :exec
DELETE FROM employees
WHERE id = $1
`

func (q *Queries) DeleteEmployee(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEmployee, id)
	return err
}

const getEmployeeByID = `-- name: GetEmployeeByID :one
SELECT
    e.id,
    e.org_id,
    e.user_id,
    e.department_id,
    e.position_id,
    e.role,
    e.salary_rate,
    e.status,
    u.first_name,
    u.last_name,
    u.email,
    u.phone_number,
    d.name AS department_name,
    p.name AS position_name
FROM employees e
         JOIN users       u ON u.id = e.user_id
         JOIN departments d ON d.id = e.department_id
         JOIN positions   p ON p.id = e.position_id
WHERE e.id = $1
`

type GetEmployeeByIDRow struct {
	ID             uuid.UUID `json:"id"`
	OrgID          uuid.UUID `json:"org_id"`
	UserID         uuid.UUID `json:"user_id"`
	DepartmentID   uuid.UUID `json:"department_id"`
	PositionID     uuid.UUID `json:"position_id"`
	Role           string    `json:"role"`
	SalaryRate     string    `json:"salary_rate"`
	Status         string    `json:"status"`
	FirstName      string    `json:"first_name"`
	LastName       string    `json:"last_name"`
	Email          string    `json:"email"`
	PhoneNumber    string    `json:"phone_number"`
	DepartmentName string    `json:"department_name"`
	PositionName   string    `json:"position_name"`
}

func (q *Queries) GetEmployeeByID(ctx context.Context, id uuid.UUID) (GetEmployeeByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEmployeeByID, id)
	var i GetEmployeeByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.DepartmentID,
		&i.PositionID,
		&i.Role,
		&i.SalaryRate,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.PhoneNumber,
		&i.DepartmentName,
		&i.PositionName,
	)
	return i, err
}

const getEmployeesByOrgID = `-- name: GetEmployeesByOrgID :many
SELECT
    e.id,
    e.org_id,
    e.user_id,
    e.department_id,
    e.position_id,
    e.role,
    e.salary_rate,
    e.status,
    u.first_name,
    u.last_name,
    u.email,
    u.phone_number,
    d.name AS department_name,
    p.name AS position_name
FROM employees e
         JOIN users       u ON u.id = e.user_id
         JOIN departments d ON d.id = e.department_id
         JOIN positions   p ON p.id = e.position_id
WHERE e.org_id = $1
ORDER BY u.last_name, u.first_name
`

type GetEmployeesByOrgIDRow struct {
	ID             uuid.UUID `json:"id"`
	OrgID          uuid.UUID `json:"org_id"`
	UserID         uuid.UUID `json:"user_id"`
	DepartmentID   uuid.UUID `json:"department_id"`
	PositionID     uuid.UUID `json:"position_id"`
	Role           string    `json:"role"`
	SalaryRate     string    `json:"salary_rate"`
	Status         string    `json:"status"`
	FirstName      string    `json:"first_name"`
	LastName       string    `json:"last_name"`
	Email          string    `json:"email"`
	PhoneNumber    string    `json:"phone_number"`
	DepartmentName string    `json:"department_name"`
	PositionName   string    `json:"position_name"`
}

func (q *Queries) GetEmployeesByOrgID(ctx context.Context, orgID uuid.UUID) ([]GetEmployeesByOrgIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getEmployeesByOrgID, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEmployeesByOrgIDRow{}
	for rows.Next() {
		var i GetEmployeesByOrgIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.DepartmentID,
			&i.PositionID,
			&i.Role,
			&i.SalaryRate,
			&i.Status,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PhoneNumber,
			&i.DepartmentName,
			&i.PositionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrgIDByUserID = `-- name: GetOrgIDByUserID :one
SELECT org_id FROM users WHERE id = $1
`

func (q *Queries) GetOrgIDByUserID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getOrgIDByUserID, id)
	var org_id uuid.UUID
	err := row.Scan(&org_id)
	return org_id, err
}

const insertEmployee = `-- name: InsertEmployee :exec
INSERT INTO employees (
    id,
    org_id,
    user_id,
    department_id,
    position_id,
    role,
    salary_rate,
    status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertEmployeeParams struct {
	ID           uuid.UUID `json:"id"`
	OrgID        uuid.UUID `json:"org_id"`
	UserID       uuid.UUID `json:"user_id"`
	DepartmentID uuid.UUID `json:"department_id"`
	PositionID   uuid.UUID `json:"position_id"`
	Role         string    `json:"role"`
	SalaryRate   string    `json:"salary_rate"`
	Status       string    `json:"status"`
}

func (q *Queries) InsertEmployee(ctx context.Context, arg InsertEmployeeParams) error {
	_, err := q.db.ExecContext(ctx, insertEmployee,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.DepartmentID,
		arg.PositionID,
		arg.Role,
		arg.SalaryRate,
		arg.Status,
	)
	return err
}

const updateEmployeeDepartment = `-- name: UpdateEmployeeDepartment :exec
UPDATE employees
SET department_id = $2
WHERE id = $1
`

type UpdateEmployeeDepartmentParams struct {
	ID           uuid.UUID `json:"id"`
	DepartmentID uuid.UUID `json:"department_id"`
}

func (q *Queries) UpdateEmployeeDepartment(ctx context.Context, arg UpdateEmployeeDepartmentParams) error {
	_, err := q.db.ExecContext(ctx, updateEmployeeDepartment, arg.ID, arg.DepartmentID)
	return err
}

const updateEmployeePosition = `-- name: UpdateEmployeePosition :exec
UPDATE employees
SET position_id = $2
WHERE id = $1
`

type UpdateEmployeePositionParams struct {
	ID         uuid.UUID `json:"id"`
	PositionID uuid.UUID `json:"position_id"`
}

func (q *Queries) UpdateEmployeePosition(ctx context.Context, arg UpdateEmployeePositionParams) error {
	_, err := q.db.ExecContext(ctx, updateEmployeePosition, arg.ID, arg.PositionID)
	return err
}

const updateEmployeeRole = `-- name: UpdateEmployeeRole :exec
UPDATE employees
SET role = $2
WHERE id = $1
`

type UpdateEmployeeRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

func (q *Queries) UpdateEmployeeRole(ctx context.Context, arg UpdateEmployeeRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateEmployeeRole, arg.ID, arg.Role)
	return err
}

const updateEmployeeSalary = `-- name: UpdateEmployeeSalary :exec
UPDATE employees
SET salary_rate = $2
WHERE id = $1
`

type UpdateEmployeeSalaryParams struct {
	ID         uuid.UUID `json:"id"`
	SalaryRate string    `json:"salary_rate"`
}

func (q *Queries) UpdateEmployeeSalary(ctx context.Context, arg UpdateEmployeeSalaryParams) error {
	_, err := q.db.ExecContext(ctx, updateEmployeeSalary, arg.ID, arg.SalaryRate)
	return err
}

const updateEmployeeStatus = `-- name: UpdateEmployeeStatus :exec
UPDATE employees
SET status = $2
WHERE id = $1
`

type UpdateEmployeeStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateEmployeeStatus(ctx context.Context, arg UpdateEmployeeStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateEmployeeStatus, arg.ID, arg.Status)
	return err
}
