// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	CheckVATUnique(ctx context.Context, vatID string) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	InsertConsent(ctx context.Context, arg InsertConsentParams) error
	InsertOrganization(ctx context.Context, arg InsertOrganizationParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
	UpdateUserVerificationStatus(ctx context.Context, email string) error
}

var _ Querier = (*Queries)(nil)
