// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const checkVATUnique = `-- name: CheckVATUnique :one
SELECT COUNT(*)
FROM organizations
WHERE vat_id = $1
`

func (q *Queries) CheckVATUnique(ctx context.Context, vatID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkVATUnique, vatID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmployeesByDepartment = `-- name: CountEmployeesByDepartment :one
SELECT COUNT(*)
FROM employees
WHERE department_id = $1
`

func (q *Queries) CountEmployeesByDepartment(ctx context.Context, departmentID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmployeesByDepartment, departmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmployeesByPosition = `-- name: CountEmployeesByPosition :one
SELECT COUNT(*)
FROM employees
WHERE position_id = $1
`

func (q *Queries) CountEmployeesByPosition(ctx context.Context, positionID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmployeesByPosition, positionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM departments WHERE id = $1 AND org_id = $2
`

type DeleteDepartmentParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeleteDepartment(ctx context.Context, arg DeleteDepartmentParams) error {
	_, err := q.db.ExecContext(ctx, deleteDepartment, arg.ID, arg.OrgID)
	return err
}

const deletePosition = `-- name: DeletePosition :exec
DELETE FROM positions WHERE id = $1 AND org_id = $2
`

type DeletePositionParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

func (q *Queries) DeletePosition(ctx context.Context, arg DeletePositionParams) error {
	_, err := q.db.ExecContext(ctx, deletePosition, arg.ID, arg.OrgID)
	return err
}

const getDepartmentsByOrgID = `-- name: GetDepartmentsByOrgID :many
SELECT id, org_id, name FROM departments WHERE org_id = $1 ORDER BY name
`

func (q *Queries) GetDepartmentsByOrgID(ctx context.Context, orgID uuid.UUID) ([]Department, error) {
	rows, err := q.db.QueryContext(ctx, getDepartmentsByOrgID, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(&i.ID, &i.OrgID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getPositionsByOrgID = `-- name: GetPositionsByOrgID :many
SELECT id, org_id, name FROM positions WHERE org_id = $1 ORDER BY name
`

func (q *Queries) GetPositionsByOrgID(ctx context.Context, orgID uuid.UUID) ([]Position, error) {
	rows, err := q.db.QueryContext(ctx, getPositionsByOrgID, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(&i.ID, &i.OrgID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, org_id, verification_status
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID                 uuid.UUID `json:"id"`
	OrgID              uuid.UUID `json:"org_id"`
	VerificationStatus string    `json:"verification_status"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.ID, &i.OrgID, &i.VerificationStatus)
	return i, err
}

const insertConsent = `-- name: InsertConsent :exec
INSERT INTO consents (
    id, user_id, org_id, document_type, version,
    created_at
)
VALUES (
           $1, $2, $3, $4, $5, NOW()
       )
`

type InsertConsentParams struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	OrgID        uuid.UUID `json:"org_id"`
	DocumentType string    `json:"document_type"`
	Version      string    `json:"version"`
}

func (q *Queries) InsertConsent(ctx context.Context, arg InsertConsentParams) error {
	_, err := q.db.ExecContext(ctx, insertConsent,
		arg.ID,
		arg.UserID,
		arg.OrgID,
		arg.DocumentType,
		arg.Version,
	)
	return err
}

const insertDepartment = `-- name: InsertDepartment :exec
INSERT INTO departments (
    id, org_id, name
)
VALUES (
        $1, $2, $3
)
`

type InsertDepartmentParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
	Name  string    `json:"name"`
}

func (q *Queries) InsertDepartment(ctx context.Context, arg InsertDepartmentParams) error {
	_, err := q.db.ExecContext(ctx, insertDepartment, arg.ID, arg.OrgID, arg.Name)
	return err
}

const insertOrganization = `-- name: InsertOrganization :exec
INSERT INTO organizations (
    id,
    admin_id,
    name,
    vat_id,
    description,
    address,
    city_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertOrganizationParams struct {
	ID          uuid.UUID `json:"id"`
	AdminID     uuid.UUID `json:"admin_id"`
	Name        string    `json:"name"`
	VatID       string    `json:"vat_id"`
	Description string    `json:"description"`
	Address     string    `json:"address"`
	CityID      int32     `json:"city_id"`
}

func (q *Queries) InsertOrganization(ctx context.Context, arg InsertOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, insertOrganization,
		arg.ID,
		arg.AdminID,
		arg.Name,
		arg.VatID,
		arg.Description,
		arg.Address,
		arg.CityID,
	)
	return err
}

const insertPosition = `-- name: InsertPosition :exec
INSERT INTO positions (
    id, org_id, name
)
VALUES (
        $1, $2, $3
)
`

type InsertPositionParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
	Name  string    `json:"name"`
}

func (q *Queries) InsertPosition(ctx context.Context, arg InsertPositionParams) error {
	_, err := q.db.ExecContext(ctx, insertPosition, arg.ID, arg.OrgID, arg.Name)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (
    id,
    org_id,
    email,
    role,
    first_name,
    last_name,
    phone_number,
    verification_status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'Unverified')
`

type InsertUserParams struct {
	ID          uuid.UUID `json:"id"`
	OrgID       uuid.UUID `json:"org_id"`
	Email       string    `json:"email"`
	Role        string    `json:"role"`
	FirstName   string    `json:"first_name"`
	LastName    string    `json:"last_name"`
	PhoneNumber string    `json:"phone_number"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser,
		arg.ID,
		arg.OrgID,
		arg.Email,
		arg.Role,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
	)
	return err
}

const updateUserVerificationStatus = `-- name: UpdateUserVerificationStatus :exec
UPDATE users
SET verification_status = 'Verified'
WHERE email = $1
`

func (q *Queries) UpdateUserVerificationStatus(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, updateUserVerificationStatus, email)
	return err
}
