// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const checkVATUnique = `-- name: CheckVATUnique :one
SELECT COUNT(*)
FROM organizations
WHERE vat_id = $1
`

func (q *Queries) CheckVATUnique(ctx context.Context, vatID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkVATUnique, vatID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, org_id, verification_status
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID                 uuid.UUID `json:"id"`
	OrgID              uuid.UUID `json:"org_id"`
	VerificationStatus string    `json:"verification_status"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(&i.ID, &i.OrgID, &i.VerificationStatus)
	return i, err
}

const insertConsent = `-- name: InsertConsent :exec
INSERT INTO consents (
    id, user_id, org_id, document_type, version,
    created_at
)
VALUES (
           $1, $2, $3, $4, $5, NOW()
       )
`

type InsertConsentParams struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	OrgID        uuid.UUID `json:"org_id"`
	DocumentType string    `json:"document_type"`
	Version      string    `json:"version"`
}

func (q *Queries) InsertConsent(ctx context.Context, arg InsertConsentParams) error {
	_, err := q.db.ExecContext(ctx, insertConsent,
		arg.ID,
		arg.UserID,
		arg.OrgID,
		arg.DocumentType,
		arg.Version,
	)
	return err
}

const insertOrganization = `-- name: InsertOrganization :exec
INSERT INTO organizations (
    id,
    admin_id,
    name,
    vat_id,
    description,
    address,
    city_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertOrganizationParams struct {
	ID          uuid.UUID `json:"id"`
	AdminID     uuid.UUID `json:"admin_id"`
	Name        string    `json:"name"`
	VatID       string    `json:"vat_id"`
	Description string    `json:"description"`
	Address     string    `json:"address"`
	CityID      int32     `json:"city_id"`
}

func (q *Queries) InsertOrganization(ctx context.Context, arg InsertOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, insertOrganization,
		arg.ID,
		arg.AdminID,
		arg.Name,
		arg.VatID,
		arg.Description,
		arg.Address,
		arg.CityID,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (
    id,
    org_id,
    email,
    role,
    first_name,
    last_name,
    phone_number,
    verification_status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'Unverified')
`

type InsertUserParams struct {
	ID          uuid.UUID `json:"id"`
	OrgID       uuid.UUID `json:"org_id"`
	Email       string    `json:"email"`
	Role        string    `json:"role"`
	FirstName   string    `json:"first_name"`
	LastName    string    `json:"last_name"`
	PhoneNumber string    `json:"phone_number"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser,
		arg.ID,
		arg.OrgID,
		arg.Email,
		arg.Role,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
	)
	return err
}

const updateUserVerificationStatus = `-- name: UpdateUserVerificationStatus :exec
UPDATE users
SET verification_status = 'Verified'
WHERE email = $1
`

func (q *Queries) UpdateUserVerificationStatus(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, updateUserVerificationStatus, email)
	return err
}
